In [63]:
# Import library
import pandas as pd
import numpy as np

from sklearn.preprocessing import Imputer, LabelEncoder, OneHotEncoder, StandardScaler
    

In [2]:
data = pd.read_csv('Data.csv')

In [7]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [55]:
X = data.iloc[:,:-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [56]:
y = data.iloc[:, -1].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [57]:
imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [58]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [59]:
label_encoder = LabelEncoder()
X[:, 0] =label_encoder.fit_transform(X[:,0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [60]:
one_hot_encoder = OneHotEncoder(categorical_features=[0])
X = one_hot_encoder.fit_transform(X).toarray()
df = pd.DataFrame(X)
df

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


0    1    2          3             4
0  1.0  0.0  0.0  44.000000  72000.000000
1  0.0  0.0  1.0  27.000000  48000.000000
2  0.0  1.0  0.0  30.000000  54000.000000
3  0.0  0.0  1.0  38.000000  61000.000000
4  0.0  1.0  0.0  40.000000  63777.777778
5  1.0  0.0  0.0  35.000000  58000.000000
6  0.0  0.0  1.0  38.777778  52000.000000
7  1.0  0.0  0.0  48.000000  79000.000000
8  0.0  1.0  0.0  50.000000  83000.000000
9  1.0  0.0  0.0  37.000000  67000.000000

In [61]:
X =X.astype(int)
X

array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 61000],
       [    0,     1,     0,    40, 63777],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [64]:
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[ 1.22474487e+00, -6.54653671e-01, -6.54653671e-01,
         7.69734393e-01,  7.49480344e-01],
       [-8.16496581e-01, -6.54653671e-01,  1.52752523e+00,
        -1.69922498e+00, -1.43817132e+00],
       [-8.16496581e-01,  1.52752523e+00, -6.54653671e-01,
        -1.26352627e+00, -8.91258402e-01],
       [-8.16496581e-01, -6.54653671e-01,  1.52752523e+00,
        -1.01663033e-01, -2.53193334e-01],
       [-8.16496581e-01,  1.52752523e+00, -6.54653671e-01,
         1.88802776e-01, -6.38065068e-05],
       [ 1.22474487e+00, -6.54653671e-01, -6.54653671e-01,
        -5.37361746e-01, -5.26649792e-01],
       [-8.16496581e-01, -6.54653671e-01,  1.52752523e+00,
        -1.01663033e-01, -1.07356271e+00],
       [ 1.22474487e+00, -6.54653671e-01, -6.54653671e-01,
         1.35066601e+00,  1.38754541e+00],
       [-8.16496581e-01,  1.52752523e+00, -6.54653671e-01,
         1.64113182e+00,  1.75215402e+00],
       [ 1.22474487e+00, -6.54653671e-01, -6.54653671e-01,
        -2.46895937e-01